name: car-sharing-push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build  Docker image
        run: docker build . -t $REGISTRY/car-sharing-drives
        
      - name: Push  Docker image
        run: docker image push $REGISTRY/car-sharing-drives
